name: Publish to CDN

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [ 21.x ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Install dependencies
        run: pnpm i

      - name: Build
        run: pnpm run build

      - name: Test
        run: pnpm test

      - name: Define Job Variables from package.json
        run: |
          NAME=$(node -e "console.log(require('./package.json').name)")
          VERSION=$(node -e "console.log(require('./package.json').version)")
          MAJOR_VERSION=$(echo $VERSION | cut -d '.' -f 1)
          echo "Name: $NAME"
          echo "Version: $VERSION"
          echo "Major Version: $MAJOR_VERSION"
          echo "NAME=$NAME" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "MAJOR_VERSION=$MAJOR_VERSION" >> $GITHUB_ENV

      - name: Clone CDN repository
        run: git clone https://github.com/groupby/cdn.git cdn

      - name: Copy dist files to CDN repository
        run: |
          JS_FILE_NAME="${NAME}-${VERSION}.min.js"
          JS_MAP_FILE_NAME="${JS_FILE_NAME}.map"
          TYPES_FILE_NAME="${NAME}-${VERSION}.d.ts"
          
          JS_MAJOR_FILE_NAME="${NAME}-${MAJOR_VERSION}.min.js"
          JS_MAJOR_MAP_FILE_NAME="${JS_MAJOR_FILE_NAME}.map"
          TYPES_MAJOR_FILE_NAME="${NAME}-${MAJOR_VERSION}.d.ts"
          
          DIST_DIR="dist"
          CDN_DIR="cdn/static/javascript"
          
          echo "JS_FILE_NAME: $JS_FILE_NAME"
          echo "JS_MAP_FILE_NAME: $JS_MAP_FILE_NAME"
          echo "TYPES_FILE_NAME: $TYPES_FILE_NAME"
          echo "JS_MAJOR_FILE_NAME: $JS_MAJOR_FILE_NAME"
          echo "JS_MAJOR_MAP_FILE_NAME: $JS_MAJOR_MAP_FILE_NAME"
          echo "TYPES_MAJOR_FILE_NAME: $TYPES_MAJOR_FILE_NAME"
          
          cp "${DIST_DIR}/${JS_FILE_NAME}" "${CDN_DIR}/${JS_FILE_NAME}"
          cp "${DIST_DIR}/${JS_MAP_FILE_NAME}" "${CDN_DIR}/${JS_MAP_FILE_NAME}"
          cp "${DIST_DIR}/${TYPES_FILE_NAME}" "${CDN_DIR}/${TYPES_FILE_NAME}"

          cp "${DIST_DIR}/${JS_MAJOR_FILE_NAME}" "${CDN_DIR}/${JS_MAJOR_FILE_NAME}"
          cp "${DIST_DIR}/${JS_MAJOR_MAP_FILE_NAME}" "${CDN_DIR}/${JS_MAJOR_MAP_FILE_NAME}"
          cp "${DIST_DIR}/${TYPES_MAJOR_FILE_NAME}" "${CDN_DIR}/${TYPES_MAJOR_FILE_NAME}"

      - name: Push lib files to new branch in CDN repository
        working-directory: cdn
        run: |
          git checkout -b "${NAME}-${VERSION}"
          git add "static/javascript/${NAME}-*.js"
          git add "static/javascript/${NAME}-*.map"
          git add "static/javascript/${NAME}-*.d.ts"
          git commit -m "Release ${NAME} v${VERSION}"
          git push -u origin HEAD
          
