name: Publish to CDN

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [ 21.x ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Install dependencies
        run: pnpm i

      - name: Build
        run: pnpm run build

      - name: Test
        run: pnpm test

      - name: Clone new repository
        run: git clone https://github.com/groupby/cdn.git cdn

      - name: Commit and push changes
        working-directory: cdn
        run: |
          NAME=$(node -e "console.log(require('../package.json').name)")
          VERSION=$(node -e "console.log(require('../package.json').version)")
          MAJOR_VERSION=$(echo $VERSION | cut -d '.' -f 1)
          echo "Name: $NAME"
          echo "Version: $VERSION"
          echo "Major Version: $MAJOR_VERSION"
          echo "Current Name: $CUR_NAME"
        env:
          CUR_NAME: $(node -e "console.log(require('./package.json').name)")