name: Publish to NPM

on:
  workflow_dispatch:
    inputs:
      changesLevel:
        description: 'Level of changes'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - patch
          - minor
          - major

jobs:
  build-and-publish:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [ 21.x ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Install dependencies
        run: pnpm i

      - name: Build
        run: pnpm run build:${{ github.event.inputs.changesLevel }} --if-present

      - name: Test
        run: pnpm test

      - name: Publish to NPM
        run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}